package com.azet.KitchenAssistant.Entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;


@Entity
@Table(name = "product")
@Getter
@Setter
public class Product {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    private String name;

    private String image;    //route or url generated by AI

    private String codeBar;

    @ManyToOne
    @JoinColumn(name= "category_id")
    private Category category;

    @OneToOne(cascade = CascadeType.ALL, mappedBy = "product")
    private Nutrient nutrients;
}
